letters25/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from letters_collection import urls as letters_urls
from django.conf import settings
from django.conf.urls import patterns
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^adminadmin/', include(admin.site.urls)),
    url(r'^', include(letters_urls, namespace='letters')),
]

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = patterns('',
        url(r'^filer_public_thumbnails/(?P<path>.*)$', 'django.views.static.serve',  # NOQA
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ) + staticfiles_urlpatterns() + urlpatterns  # NOQA

letters_collection/urls.py
from django.conf.urls import url
from .views import IndexView, CategoriesView, CategoryView, LetterView, AboutUsView, SubmitView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='home'),
    url(r'^popular/$', IndexView.as_view(letters_list='popular'), name='popular'),
    url(r'^categories/$', CategoriesView.as_view(), name='categories'),
    url(r'^categories/(?P<category>[\w-]+)/(?P<interval>[\w-]+)/$', CategoryView.as_view(), name='category_detail'),
    url(r'^letters/(?P<slug>[\w-]+)/$', LetterView.as_view(), name='letter'),
    url(r'^project/$', AboutUsView.as_view(), name='project'),
    url(r'^submit/$', SubmitView.as_view(), name='submit'),
]

letters_collection/models.py
from django.db import models
from filer.fields.image import FilerImageField
from markupfield.fields import MarkupField
from django.utils import timezone


class Letter(models.Model):
    author = models.CharField(max_length=255, help_text='Author of the letter')
    slug = models.SlugField(max_length=100, unique=True, help_text='URL slug for this letter')
    occupation = models.CharField(max_length=100, help_text="Author's occupation")
    age = models.IntegerField(help_text="Author's age")
    location = models.CharField(max_length=100, help_text="Author's location")
    illustration = FilerImageField(
        null=True,
        blank=True,
        help_text='Illustration for this letter',
        related_name="letter_illustration"
        )
    letter = MarkupField(default_markup_type='markdown', help_text='The letter itself')
    letter_length = models.IntegerField(
        blank=True,
        help_text='What is the approximate reading length of this letter. Leave empty for autofill.'
        )
    published = models.BooleanField(default=False, help_text='Should this letter be published?')
    popularity_index = models.IntegerField(
        blank=True,
        default=0,
        help_text='The letter with higher index, will be shown as more popular. \
        (This is only a temporary measure, until I automate it)'
        )
    timestamp_created = models.DateTimeField(auto_now_add=True)
    timestamp_edited = models.DateTimeField(auto_now=True)
    timestamp_published = models.DateTimeField(
        blank=True,
        default=timezone.now,
        help_text='When was this letter published (leave empty for auto-fill)'
        )
    submission = models.ForeignKey(
        'letters_collection.LetterSubmission',
        null=True,
        blank=True,
        help_text='Submission for this letter',
        related_name='letter_object'
        )

    class Meta:
        ordering = ['-timestamp_created']

    def __unicode__(self):
        return self.author

    def save(self, *args, **kwargs):
        # Fill in self.letter_length if it is empty
        if not self.letter_length:
            self.letter_length = self.get_reading_length()
        super(Letter, self).save(*args, **kwargs)

    def get_reading_length(self):
        """
        Return estimated reading length of this letter rounded up to the minute.
        """
        number_of_char = len(self.letter.raw)
        estimate = number_of_char / 1000  # Estimated reading length in minutes
        estimate = round(estimate)
        return estimate
        # return '%s min' % estimate if estimate else '< 1 min'


class LetterSubmission(models.Model):
    author = models.CharField(max_length=255, help_text='Your first and last name')
    email = models.EmailField(help_text='Your email')
    occupation = models.CharField(max_length=100, help_text="Your occupation")
    age = models.IntegerField(help_text="Your age")
    location = models.CharField(max_length=100, help_text="Your location")
    letter = models.TextField(help_text='The letter itself')
    timestamp_created = models.DateTimeField(auto_now_add=True)
    timestamp_edited = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-timestamp_created']

    def __unicode__(self):
        return self.author

letters_collection/forms.py
from django.forms import ModelForm, Textarea, CharField, ValidationError
from .models import LetterSubmission


class SubmissionForm(ModelForm):
    phonenumber = CharField(required=False, label='phonenumber')  # This is honey pot, but named differently, to not be too obvious

    class Meta:
        model = LetterSubmission
        fields = ['author', 'age', 'occupation', 'location', 'letter', 'email']
        widgets = {
            'letter': Textarea(attrs={'rows': 4})
        }

    def __init__(self, *args, **kwargs):
        super(SubmissionForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-submit'})

# TODO On save send notification to the author and to our team

letters_collection/views.py
from django.views.generic import ListView, DetailView, TemplateView, FormView
from django.core.urlresolvers import reverse_lazy
from django.http import Http404
from .models import Letter
from .forms import SubmissionForm
from .actions import notify_author, notify_team


class IndexView(ListView):
    model = Letter
    template_name = 'index.html'
    letters_list = 'latest'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        # For admins show the latest letter
        # For normal users show the latest published letter
        featured = Letter.objects.all() if self.request.user.is_superuser else Letter.objects.filter(published=True)
        featured = featured.latest('timestamp_published')

        if self.letters_list == 'popular':
            featured = Letter.objects.filter(published=True).order_by(
                '-popularity_index',
                '-timestamp_published',
                '-timestamp_created'
                )[0]
        submitted = self.request.GET.get('submitted')
        context.update({'featured': featured, 'submitted': submitted})
        return context

    def get_queryset(self):
        # For admins show all the letters but for normal users show only published letters
        qs = Letter.objects.all() if self.request.user.is_superuser else Letter.objects.filter(published=True)
        if self.letters_list == 'latest':
            return qs.order_by('-timestamp_published', '-timestamp_created')
        elif self.letters_list == 'popular':
            return qs.order_by('-popularity_index', '-timestamp_published', '-timestamp_created')[:15]


class CategoriesView(TemplateView):
    template_name = 'categories.html'

    def get_context_data(self, **kwargs):
        context = super(CategoriesView, self).get_context_data(**kwargs)
        selected = self.request.GET.get('category', 'age')
        context.update({
            'selected': selected,
            'five_min_letters': Letter.objects.filter(letter_length__lt=5).count(),
            'ten_min_letters': Letter.objects.filter(letter_length__lt=10, letter_length__gte=5).count(),
            'fifteen_min_letters': Letter.objects.filter(letter_length__gte=10).count()
        })
        return context


class CategoryView(ListView):
    model = Letter
    template_name = 'category_detail.html'
    interval = []
    selected = ''

    def get_queryset(self):
        category = self.kwargs.get('category')
        interval = self.kwargs.get('interval')
        self.selected = category
        try:
            interval = interval.split('-')
            if len(interval) > 2 or len(interval) < 1:
                raise Http404
            self.interval = interval
            interval = [int(i) for i in interval]
        except:
            raise Http404
        if category == 'age':
            letters = Letter.objects.filter(published=True).filter(age__gte=interval[0])
            if len(interval) == 2:
                letters = letters.filter(age__lte=interval[1])
            return letters.order_by('age', '-timestamp_published')
        elif category == 'length':
            letters = Letter.objects.filter(published=True).filter(letter_length__gte=interval[0])
            if len(interval) == 2:
                letters = letters.filter(letter_length__lt=interval[1])
            return letters.order_by('letter_length', '-timestamp_published')
        else:
            raise Http404

    def get_context_data(self, **kwargs):
        context = super(CategoryView, self).get_context_data(**kwargs)
        if self.selected == 'length':
            value = " - ".join(self.interval) + ' min'
        else:
            value = " - ".join(self.interval)
        context.update({'value': value, 'selected': self.selected})
        return context


class LetterView(DetailView):
    model = Letter
    template_name = 'letter_detail.html'

    def get_queryset(self):
        # For admins show all the letters but for normal users show only published letters
        qs = Letter.objects.all() if self.request.user.is_superuser else Letter.objects.filter(published=True)
        return qs.order_by('-timestamp_published', '-timestamp_created')

    def get_context_data(self, **kwargs):
        context = super(LetterView, self).get_context_data(**kwargs)
        try:
            next_letter = self.object.get_next_by_timestamp_published(published=True)
        except Exception:
            next_letter = Letter.objects.filter(published=True).earliest('timestamp_published')
        try:
            previous_letter = self.object.get_previous_by_timestamp_published(published=True)
        except Exception:
            previous_letter = Letter.objects.filter(published=True).latest('timestamp_published')
        context.update({
            'next_letter': next_letter,
            'previous_letter': previous_letter
        })
        return context


class AboutUsView(TemplateView):
    template_name = 'about_us.html'


class SubmitView(FormView):
    form_class = SubmissionForm
    template_name = 'submit.html'
    success_url = '/?submitted=1'

    def form_valid(self, form):
        if not form.cleaned_data['phonenumber']:  # Check the honeypot
            # Save the Submission
            obj = form.save()
            # Send an email to author
            notify_author(obj)
            # Notify the letters team
            notify_team(obj)
        else:
            print "Gotcha!"
        return super(SubmitView, self).form_valid(form)

letters_collection/templates/base.html
{% load pipeline active_tag static %}
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{% block title %}Letters to My 25-Year-Old-Self{% endblock %}</title>
        <meta name="description" content="Here is a collection of letters filled with the dreams, fears, and revelations of incredible people around the world. If you could tell your 25-year-old self anything at all, what would you say?">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="apple-touch-icon" sizes="57x57" href="/static/apple-touch-icon-57x57.png">
        <link rel="apple-touch-icon" sizes="60x60" href="/static/apple-touch-icon-60x60.png">
        <link rel="apple-touch-icon" sizes="72x72" href="/static/apple-touch-icon-72x72.png">
        <link rel="apple-touch-icon" sizes="76x76" href="/static/apple-touch-icon-76x76.png">
        <link rel="apple-touch-icon" sizes="114x114" href="/static/apple-touch-icon-114x114.png">
        <link rel="apple-touch-icon" sizes="120x120" href="/static/apple-touch-icon-120x120.png">
        <link rel="apple-touch-icon" sizes="144x144" href="/static/apple-touch-icon-144x144.png">
        <link rel="apple-touch-icon" sizes="152x152" href="/static/apple-touch-icon-152x152.png">
        <link rel="apple-touch-icon" sizes="180x180" href="/static/apple-touch-icon-180x180.png">
        <link rel="icon" type="image/png" href="/static/favicon-32x32.png" sizes="32x32">
        <link rel="icon" type="image/png" href="/static/favicon-194x194.png" sizes="194x194">
        <link rel="icon" type="image/png" href="/static/favicon-96x96.png" sizes="96x96">
        <link rel="icon" type="image/png" href="/static/android-chrome-192x192.png" sizes="192x192">
        <link rel="icon" type="image/png" href="/static/favicon-16x16.png" sizes="16x16">
        <link rel="manifest" href="/static/manifest.json">
        <link rel="shortcut icon" href="/static/favicon.ico">
        <meta name="msapplication-TileColor" content="#2b5797">
        <meta name="msapplication-TileImage" content="/static/mstile-144x144.png">
        <meta name="msapplication-config" content="/static/browserconfig.xml">
        <meta name="theme-color" content="#ffffff">

        {% stylesheet 'pace' %}
        {% stylesheet 'custom' %}
        {% stylesheet 'font-awesome' %}

        {% javascript 'pace' %}

        {% block extra_css %}
        {% endblock extra_css %}

        {% if not debug %}
          <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
          <script>
              (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
              function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
              e=o.createElement(i);r=o.getElementsByTagName(i)[0];
              e.src='//www.google-analytics.com/analytics.js';
              r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
              ga('create','UA-42301112-1','auto');ga('send','pageview');
          </script>
        {% endif %}
        <!--[if lt IE 8]>   
        <script src="js/vendor/modernizr-2.8.3-respond-1.4.2.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'letters:home' %}"><img src="{% static 'img/new-logo.png' %}" alt="Letters to my 25-year-old self logo"></a>
        </div>
        <div class="navbar-collapse collapse" id="navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class="{% add_active request 'letters:home;letters:popular;letters:categories' '/categories/' %}"><a href="{% url 'letters:home' %}">
            <span class="img-navbar-alt">Letters</span>
            <img class="img-navbar" src="{% static 'img/red_mailbox_menu.png' %}" alt="Letters">
            </a></li>
            <li class="{% add_active request 'letters:project' %}"><a href="{% url 'letters:project' %}">
            <span class="img-navbar-alt">About</span>
            <img class="img-navbar" src="{% static 'img/my25-18.png' %}" alt="Project">
            </a></li>
            <li class="{% add_active request 'letters:submit' %}"><a href="{% url 'letters:submit' %}">
            <span class="img-navbar-alt">Submit</span>
            <img class="img-navbar" src="{% static 'img/mailbox_menu.png' %}" alt="Submit">
            </a></li>
          </ul>
          
        </div><!--/.navbar-collapse -->
      </div>
    </nav>
    {% block social_links %}
    <div class="social-media-list">
      <a href="http://www.facebook.com/LettersToMy25YearOldSelf"><i class="fa fa-lg fa-fw fa-facebook"></i></a>
      <a href="http://twitter.com/25yearoldself"><i class="fa fa-lg fa-fw fa-twitter"></i></a>
      <a href="http://letterstomy25yearoldself.tumblr.com/"><i class="fa fa-lg fa-fw fa-tumblr"></i></a>
      {# <a href="#"><i class="fa fa-lg fa-fw fa-envelope"></i></a> #}
    </div>
    {% endblock %}
    <div class="main-content">
      {% block content %}
      {% endblock content %}
    </div>

    
      <footer class="footer">
        &copy; Letters to My 25-Year-Old Self, 2015
      </footer>
    </div> <!-- /container -->

    {% javascript 'jquery' %}
    {% javascript 'vendor' %}

    {% block extra_js %}
    {% endblock extra_js %}
    </body>
</html>

letters_collection/templates/categories.html
{% extends "base.html" %}
{% load active_tag static %}

{% block extra_js %}
<script>
    $(document).ready(function () {
        $('.letters-categories-nav a').on('click', function (e) {
            e.preventDefault();
            $('.letters-categories-nav .active').removeClass('active');
            $(this).parent('li').addClass('active');

            $('.category-section').addClass('hidden');
            if ($(this).hasClass('category-age-link')) {
                $('.category-age-section').removeClass('hidden');
            } else if ($(this).hasClass('category-location-link')) {
                $('.category-location-section').removeClass('hidden');
            } else if ($(this).hasClass('category-length-link')) {
                $('.category-length-section').removeClass('hidden');
            }
        });
    });
</script>
{% endblock %}

{% block content %}
<div class="container">
<br/>
<br/>
<br/>

    <div class="row">
        <div class="col-xs-12">
            <ul class="list-inline letters-list-nav">
                <li class="{% add_active request 'letters:home' %}"><a href="{% url 'letters:home' %}">Latest</a></li>
                <li class="{% add_active request 'letters:popular' %}"><a href="{% url 'letters:popular' %}">Most Popular</a></li>
                <li class="{% add_active request 'letters:categories' '/categories/' %}"><a href="{% url 'letters:categories' %}">Categories</a></li>
            </ul>
        </div>
    </div>

    <br/>
    <div class="row">
        <div class="col-xs-12">
            <ul class="list-inline letters-categories-nav">
                <li class="{% if selected == 'age' %}active {% endif %}"><a class="category-age-link" href="{% url 'letters:categories' %}?category=age">Age</a></li>
                {# <li class="{% if selected == 'location' %}active {% endif %}"><a class="category-location-link" href="{% url 'letters:categories' %}?category=location">Location</a></li> #}
                <li class="{% if selected == 'length' %}active {% endif %}"><a class="category-length-link" href="{% url 'letters:categories' %}?category=length">Letter length</a></li>
            </ul>
        </div>
    </div>

    <br/>

    <div class="row category-section category-age-section{% if selected != 'age' %} hidden{% endif %}">
        <div class="col-xs-6 col-sm-3">
            <a href="{% url 'letters:category_detail' 'age' '0-18' %}">
                <img src="{% static 'img/icons/<18-17.png' %}" alt="Ages under 18" class="img-responsive center-block">
            </a>
        </div>
        <div class="col-xs-6 col-sm-3">
            <a href="{% url 'letters:category_detail' 'age' '19-25' %}">
                <img src="{% static 'img/icons/19-25-17.png' %}" alt="Ages between 19 and 25" class="img-responsive center-block">
            </a>
        </div>
        <div class="col-xs-6 col-sm-3">
            <a href="{% url 'letters:category_detail' 'age' '26-35' %}">
                <img src="{% static 'img/icons/26-35-17.png' %}" alt="Ages between 26 and 35" class="img-responsive center-block">
            </a>
        </div>
        <div class="col-xs-6 col-sm-3">
            <a href="{% url 'letters:category_detail' 'age' '36-45' %}">
                <img src="{% static 'img/icons/36-45-17.png' %}" alt="Ages between 36 and 45" class="img-responsive center-block">
            </a>
        </div>
        <div class="col-xs-6 col-sm-3">
            <a href="{% url 'letters:category_detail' 'age' '46-55' %}">
                <img src="{% static 'img/icons/46-55-17.png' %}" alt="Ages between 46 and 55" class="img-responsive center-block">
            </a>
        </div>
        <div class="col-xs-6 col-sm-3">
            <a href="{% url 'letters:category_detail' 'age' '56' %}">
                <img src="{% static 'img/icons/>56-17.png' %}" alt="Ages above 56" class="img-responsive center-block">
            </a>
        </div>
    </div>

    <div class="row category-section category-length-section {% if selected != 'length' %} hidden{% endif %}">
        <div class="col-xs-12 col-sm-4">
            <div class="row">
                <div class="col-xs-6">
                    <img src="{% static 'img/icons/< 5 Clock-17.png' %}" alt="Less than 5 minutes" class="img-responsive">
                </div>
                <div class="col-xs-6 col-sm-4">
                    <div class="category-length-info">
                        <div class="category-length-info-description">
                            &lt; 5 min
                            <br/>
                            {{ five_min_letters }} letters
                        </div>
                        <a href="{% url 'letters:category_detail' 'length' '0-5' %}" class="category-length-info-link">Show letters &raquo;</a>
                    </div>
                    <span class="visible-xs">
                        <br/>
                        <br/>
                    </span>
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-sm-4">
            <div class="row">
                <div class="col-xs-6">
                    <img src="{% static 'img/icons/5-10 clock-17.png' %}" alt="Between 5 and 10 minutes" class="img-responsive">
                </div>
                <div class="col-xs-6 col-sm-4">
                    <div class="category-length-info">
                        <div class="category-length-info-description">
                            5 - 10 min
                            <br/>
                            {{ ten_min_letters }} letters
                        </div>
                        <a href="{% url 'letters:category_detail' 'length' '5-10' %}" class="category-length-info-link">Show letters &raquo;</a>
                    </div>
                    <span class="visible-xs">
                        <br/>
                        <br/>
                    </span>
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-sm-4">
            <div class="row">
                <div class="col-xs-6">
                    <img src="{% static 'img/icons/10-15 clock-17.png' %}" alt="More than 10 minutes" class="img-responsive">
                </div>
                <div class="col-xs-6 col-sm-4">
                    <div class="category-length-info">
                        <div class="category-length-info-description">
                            &gt; 10 min
                            <br/>
                            {{ fifteen_min_letters }} letters
                        </div>
                        <a href="{% url 'letters:category_detail' 'length' '10' %}" class="category-length-info-link">Show letters &raquo;</a>
                    </div>
                </div>
            </div>
        </div>
    </div>


</div>
{% endblock %}

letters_collection/templates/category_detail.html
{% extends "base.html" %}
{% load active_tag thumbnail %}

{% block content %}
<div class="container">
<br/>
<br/>
<br/>

    <div class="row">
        <div class="col-xs-12">
            <ul class="list-inline letters-list-nav">
                <li class="{% add_active request 'letters:home' %}"><a href="{% url 'letters:home' %}">Latest</a></li>
                <li class="{% add_active request 'letters:popular' %}"><a href="{% url 'letters:popular' %}">Most Popular</a></li>
                <li class="{% add_active request 'letters:categories' '/categories/' %}"><a href="{% url 'letters:categories' %}">Categories</a></li>
            </ul>
        </div>
    </div>

    <br/>
    <div class="row">
        <div class="col-xs-12">
            <ul class="list-inline letters-categories-nav">
                <li class="{% add_active request '' '/age/' %}"><a class="category-age-link" href="{% url 'letters:categories' %}?category=age">Age{% if selected == "age" %} | {{ value }}{% endif %}</a></li>
                {# <li class="{% add_active request '' '/location/' %}"><a class="category-location-link" href="{% url 'letters:categories' %}?category=location">Location{% if selected == "location" %} | {{ value }}{% endif %}</a></li> #}
                <li class="{% add_active request '' '/length/' %}"><a class="category-length-link" href="{% url 'letters:categories' %}?category=length">Letter length{% if selected == "length" %} | {{ value }}{% endif %}</a></li>
            </ul>
        </div>
    </div>

    <br/>

    <div class="row">
        {% for letter in object_list %}
            <div class="col-xs-12 col-sm-4 col-md-3">
                <div class="letter-list-icon">
                    <img class="img-responsive center-block" src="{{ letter.illustration|thumbnail_url:'list-size' }}" alt="{{ letter.illustration.default_alt_text }}">
                    <a class="link-to-letter" href="{% url 'letters:letter' letter.slug %}">
                        <div class="overlay"></div>
                        <div class="letter-list-icon-link">
                        <span>
                            {{ letter.author }}, {{ letter.age }} <br/>
                            {{ letter.occupation }}, {{ letter.location }}
                        </span>
                        </div>
                    </a>
                </div>
                <a href="#" class="visible-xs-block text-center link-to-letter-mobile">
                <i class="fa fa-plus-square-o fa-lg"></i></a>
            </div>
        {% endfor %}
    </div>


</div>
{% endblock %}

letters_collection/templates/index.html
{% extends "base.html" %}
{% load thumbnail active_tag %}

{% block extra_js %}
{% if submitted %}
<script>
    $('#submitted-letter-modal').modal('show');
</script>
{% endif %}
<script>
    $(document).ready(function () {
        $('.link-to-letter-mobile').on('click', function(e) {
            e.preventDefault();
            $(this).siblings('.letter-list-icon').children('.link-to-letter').toggleClass('mobile-hover');
            $(this).children('.fa').toggleClass('fa-plus-square-o fa-minus-square-o');
        });
    });
</script>
{% endblock %}

{% block content %}
<div class="container">
<div class="hidden-xs">
<br/>
<br/>
<br/>
</div>
    <div class="row hidden-xs">
        <div class="col-xs-12">
        <div class="featured-letter">
            <img class="img-responsive inline-block center-block featured-letter-illustration" src="{{ featured.illustration|thumbnail_url:'featured' }}" alt="{{ featured.illustration.default_alt_text }}">

            <div class="letter-info inline-block text-left {% if not featured.published%}unpublished{% endif %}">
                <div class="letter-info-content">
                    {% if not featured.published%}[Unpublished]<br/>{% endif %}
                    <strong>{{ featured.author }}</strong><br/>
                    {{ featured.age }}<br/>
                    {{ featured.occupation }}<br/>
                    {{ featured.location }}<br/>
                    <br/>
                    Illustration by <br/>
                    {{ featured.illustration.author }}
                </div>
                <a class="letter-info-link" href="{% url 'letters:letter' featured.slug %}">Read more &raquo;</a>
            </div>
        </div>
        </div>
    </div>

<br/>
<br/>

    <div class="row">
        <div class="col-xs-12">
            <ul class="list-inline letters-list-nav">
                <li class="{% add_active request 'letters:home' %}"><a href="{% url 'letters:home' %}">Latest</a></li>
                <li class="{% add_active request 'letters:popular' %}"><a href="{% url 'letters:popular' %}">Most Popular</a></li>
                <li class="{% add_active request 'letters:categories' %}"><a href="{% url 'letters:categories' %}">Categories</a></li>
            </ul>
        </div>
    </div>

    <br/>

    <div class="row">
        {% for letter in object_list %}
            <div class="col-xs-12 col-sm-4 col-md-3">

                <div class="letter-list-icon">
                    <img class="img-responsive center-block" src="{{ letter.illustration|thumbnail_url:'list-size' }}" alt="{{ letter.illustration.default_alt_text }}">
                    <a class="link-to-letter {% if not letter.published%}unpublished{% endif %}" href="{% url 'letters:letter' letter.slug %}">
                        <div class="overlay"></div>
                        <div class="letter-list-icon-link">
                        <span>
                            {{ letter.author }}, {{ letter.age }} <br/>
                            {{ letter.occupation }}, {{ letter.location }}
                        </span>
                        </div>
                    </a>
                </div>
                <a href="#" class="visible-xs-block text-center link-to-letter-mobile">
                <i class="fa fa-plus-square-o fa-lg"></i></a>
            </div>
        {% endfor %}
    </div>

</div>

<button type="button" data-toggle="modal" data-target="#submitted-letter-modal" class='hidden'></button>
<div class="modal fade" id="submitted-letter-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title modal-title-submitted h3">Success!</h4>
      </div>
      <div class="modal-body">
        <p>Yay, your letter has been sent! You should soon receive an automatic confirmation email from us. If you don't, you might want to <a href="mailto:letterstomy25yearoldself@gmail.com">contact us</a> in case something went wrong.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Ok</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% endblock %}